# Generated by Django 6.0.1 on 2026-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='url',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='author',
            field=models.CharField(default='Anónimo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='quote',
            field=models.TextField(default='Anónimo'),
            preserve_default=False,
        ),
    ]
